# -*- coding: utf-8 -*-
{
    'name': "FAE Application",
    'summary':
        """
        FActuración Electronica Costa Rica
        """,
    'author': "PROINTEC",
    'license': 'LGPL-3',
    'website': "http://www.prointeccr.com",
    'category': 'Extra Tools',
    'version': '14e',
    'depends': ['base', 'sale', 'product', 'contacts', 'account', ],
    'data': [
        'views/assets.xml',
        'views/cabys_company_views.xml',        
        'views/res_company_views.xml',
        'views/identification_type_views.xml',
        'views/division_geopolitic_views.xml',
        'views/economic_activity_views.xml',
        'views/product_template_views.xml',
        'views/uom_views.xml',
        'views/reference_code_views.xml',
        'views/tax_code.xml',
        'views/account_tax_views.xml',
        'views/res_partner_views.xml',
        'views/fae_mail_views.xml',
        'views/tax_use_code.xml',
        'views/sale_terms_views.xml',
        'views/fae_incoming_document_views.xml',
        'views/sale_account_invoice_views.xml',
        'views/sale_order_views.xml',
        'views/menu_views.xml',
        'report/report_invoice.xml',
        'wizards/fae_read_local_doc_wizard.xml',        
        'data/xidentification.type.xml',
        'data/country_state.xml',
        'data/xcountry_county.xml',
        'data/xcountry_district.xml',
        'data/xeconomic.activity.xml',
        'data/uom.data.xml',
        'data/xreference.code.csv',
        'data/xreference.document.csv',
        'data/xpayment.method.csv',
        'data/xsale.condition.csv',
        'data/taxes_code_data.xml',
        'data/xexo_code.xml',
        'data/xother_charge_type.xml',
        'data/xtax_use_code.xml',
        'data/mail_fae_invoice_template.xml',
        'security/ir.model.access.csv',
        'cron_task/cron_read_email.xml',
        'cron_task/cron_fae_invoice.xml',
    ],
    'external_dependencies': {
        "python": [
            # 'xmlsig',
            'OpenSSL',
            'phonenumbers',
        ],
    },
    'qweb':[
            'static/src/xml/fae_button_load_document.xml',
        ],
    'application': True,
    'installable': True,
    'auto_install': False,
}
